name: Docker
on:
  pull_request:
    branches:
      - main
      - release

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v2.0.0

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: guilhermescherer
          password: ${{ secrets.DOCKER_PASSWORD }}